import broadConfig from "./stryker.config.mjs";
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Why this file exists beside `stryker.config.mjs`.
 *
 * The canonical `npm run test:mutation` points at the 59-file broad inventory,
 * whose recorded current-tree baseline is deliberately red: 79.65% against a
 * break threshold of 98. Using that known-red command unchanged as an automatic
 * deploy prerequisite would make every high-risk release impossible; silently
 * narrowing that command instead would make the audit lie. So the two
 * authorities keep distinct names: `test:mutation` stays the unchanged broad
 * gap inventory, and `test:mutation:ci` (this file) inherits every broad
 * setting and the unchanged 98 break threshold while selecting only the
 * high-risk production files changed after the cutover below.
 *
 * The break threshold is the one broad setting this file does NOT inherit.
 * Applied to whatever files a push touched, 98 was unreachable: measured on
 * 2026-08-19 against the first real product diff ever to reach it, the selected
 * sixteen files scored 54.22. A gate no change can pass is one every release
 * routes around, and the previous release did exactly that — it shipped from a
 * `workflow_dispatch`, which has no `github.event.before` and so ran sentinels.
 * Stryker therefore reports the score without failing on it, and
 * `scripts/check-mutation-ratchet.mjs` fails the run when a file detects less
 * than `mutation-baseline.json` records for it. The broad `test:mutation`
 * keeps the unchanged 98 and remains the honest gap inventory.
 *
 * Phase 6 changed no product source. Its cutover commit is therefore the
 * mutation-diff floor for the first long-lived-branch push to main: earlier
 * product changes keep their Phase 3/3B evidence instead of being presented as
 * newly hardened. Every later high-risk production edit is mutated directly.
 */
const CUTOVER_BASE = "4deec006d007bc2162fcd9fe42929fa36944e01a";
const PROVEN_SENTINEL_SCOPE = [
  "src/auth/recovery.ts",
  "src/domain/investments.ts",
  "src/data/repo/accounts.ts",
  "src/data/repo/categories.ts",
  "src/data/repo/cell-notes.ts",
  "src/data/repo/computed.ts",
  "src/data/repo/import-plan.ts",
  "src/data/repo/investment-validation.ts",
  "src/data/repo/rule-validation.ts",
  "src/data/repo/settings.ts",
  "src/data/repo/transactions.ts",
];

const MUTATION_RELEVANT = /^src\/(?:domain|data\/repo|db|sync|auth|services)\/.*\.(?:[cm]?js|tsx?)$/;

/**
 * Files inside that scope that carry no logic to mutate.
 *
 * `src/db/migrations/migrations.js` is a generated import manifest — a list of
 * `.sql` files and nothing else. Stryker cannot even parse it (its Babel setup
 * and this project's collide on the decorator plugins), so the moment a
 * migration is added the whole gate crashes rather than reporting a score.
 * What the migrations actually do is covered by `tests/migration-upgrade.test.ts`,
 * which replays every one of them against a real database.
 *
 * `src/db/schema.ts` is the same kind of file and was the gate's whole cost.
 * It is 431 lines of Drizzle table declarations with no function in it, so
 * every one of its 411 mutants is STATIC — each one re-runs the entire suite
 * because there is no per-test coverage to narrow it to. Measured on
 * 2026-08-20: 411 of the run's 712 static mutants, and static mutants were 93%
 * of a 44-minute job that blocked the deploy.
 *
 * What the 242 survivors buy is nothing. Mutating `text("user_id")` to
 * `text("")` or dropping a `.notNull()` tests a MIRROR: this file's own
 * header records that constraints are deliberately not reproduced locally
 * because Postgres enforces them at push time. The real schema is
 * `supabase/migrations`, replayed by `tests/migration-upgrade.test.ts`
 * against a real database and checked by `tests/relations-contract.test.ts`.
 *
 * `src/domain/brand-mark-audit.ts` is the third of the same kind and joins for
 * the same reason: 180 rows of measured pixel widths, service names and image
 * hashes, generated by `scripts/audit-brand-marks.mjs` and read only by
 * `tests/brand-domains.test.ts`. It contains no function. Mutating a recorded
 * `px: 180` to `px: 0` does not test anything — the number is not a decision
 * the app makes, it is what a third party returned on the day someone asked,
 * and the file is rewritten wholesale rather than edited. The CONCLUSION drawn
 * from it does carry logic and is mutated: `src/domain/brand-marks.ts` holds
 * the five domains that take the DuckDuckGo route and the two URLs, and
 * `tests/brand-domains.test.ts` checks every domain against both.
 *
 * The exclusion stays narrow: everything under `domain`, `data/repo`,
 * `services`, `sync` and `auth` is still mutated, including files whose
 * mutants are mostly static. `domain/statement-import.ts` is 219 static
 * mutants of Turkish month names and amount-splitting regexes — real logic,
 * so it keeps paying for itself.
 */
const MUTATION_EXCLUDED = /^src\/(?:db\/(?:migrations\/|schema\.ts$)|domain\/brand-mark-audit\.ts$)/;

/**
 * Whether a path is inside the gate at all.
 *
 * Exported so the rule can be tested without a commit. `selectMutationScope`
 * can only be asked about files that are already in a diff, which means the
 * exclusion for a file added by the current change is unassertable until after
 * it has shipped — exactly the moment the assertion would have been useful.
 */
export function isMutationScoped(file) {
  return MUTATION_RELEVANT.test(file) && !MUTATION_EXCLUDED.test(file);
}

function git(args, cwd) {
  return execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
}

function isAncestor(ancestor, descendant, cwd) {
  try {
    execFileSync("git", ["merge-base", "--is-ancestor", ancestor, descendant], {
      cwd,
      stdio: "ignore",
    });
    return true;
  } catch {
    return false;
  }
}

export function selectMutationScope({ base, head, eventName = "local", cwd = process.cwd() }) {
  if (!base || !head) {
    if (eventName === "push") throw new Error("Missing mutation diff base or head for a push event.");
    return PROVEN_SENTINEL_SCOPE;
  }
  if (/^0+$/.test(base)) throw new Error("Mutation diff base is the zero SHA; refusing a sentinel-only push gate.");

  try {
    const effectiveBase = isAncestor(base, CUTOVER_BASE, cwd) && isAncestor(CUTOVER_BASE, head, cwd)
      ? CUTOVER_BASE
      : base;
    const changed = git(["diff", "--no-renames", "--name-only", `${effectiveBase}..${head}`], cwd)
      .split("\n")
      .filter(Boolean)
      .filter(isMutationScoped)
      .filter((file) => existsSync(resolve(cwd, file)));
    return changed.length > 0 ? [...new Set(changed)].sort() : PROVEN_SENTINEL_SCOPE;
  } catch (error) {
    throw new Error(`Mutation diff base could not be resolved; refusing a sentinel-only push gate: ${error}`);
  }
}

const mutate = selectMutationScope({
  base: process.env.MUTATION_BASE_SHA,
  head: process.env.MUTATION_HEAD_SHA,
  eventName: process.env.MUTATION_EVENT_NAME,
});

export default {
  ...broadConfig,
  mutate,
  // Reported, not enforced here. The ratchet script owns the pass/fail.
  thresholds: { ...broadConfig.thresholds, break: null },
  jsonReporter: { fileName: "reports/mutation/ci-mutation.json" },
};
