export default {
  mutate: [
    "src/domain/investments.ts",
    "src/data/repo/investment-validation.ts",
    "src/auth/recovery.ts",
  ],
  ignorePatterns: [
    "/android/**",
    "/ios/**",
    "/dist/**",
    "/dist-e2e/**",
    "/graphify-out/**",
    "/.expo/**",
    "/.codex/**",
    "/.ai/**",
    "/.agents/**",
    "/.claude/**",
    "/docs/**",
    "/coverage/**",
    "/playwright-report/**",
    "/test-results/**",
  ],
  testRunner: "vitest",
  coverageAnalysis: "perTest",
  reporters: ["clear-text", "json"],
  jsonReporter: { fileName: "reports/mutation/mutation.json" },
  thresholds: { high: 99, low: 98, break: 98 },
  concurrency: 4,
  timeoutMS: 15_000,
  cleanTempDir: "always",
  vitest: { configFile: "vitest.mutation.config.ts", related: false },
};
