export default {
  mutate: [
    "src/auth/recovery.ts",
    "src/data/repo/accounts.ts",
    "src/data/repo/budgets.ts",
    "src/data/repo/categories.ts",
    "src/data/repo/cell-notes.ts",
    "src/data/repo/computed.ts",
    "src/data/repo/expected.ts",
    "src/data/repo/import-plan.ts",
    "src/data/repo/imports.ts",
    "src/data/repo/installments.ts",
    "src/data/repo/investments.ts",
    "src/data/repo/investment-validation.ts",
    "src/data/repo/maintenance.ts",
    "src/data/repo/onboarding.ts",
    "src/data/repo/rule-validation.ts",
    "src/data/repo/reset.ts",
    "src/data/repo/rules.ts",
    "src/data/repo/settings.ts",
    "src/data/repo/transactions.ts",
    "src/domain/analytics.ts",
    "src/domain/app-guard.ts",
    "src/domain/balance-declaration.ts",
    "src/domain/balance.ts",
    "src/domain/budgets.ts",
    "src/domain/card-statements.ts",
    "src/domain/cash-flow-matrix.ts",
    "src/domain/computed-columns.ts",
    "src/domain/dashboard.ts",
    "src/domain/dates.ts",
    "src/domain/diagnostics.ts",
    "src/domain/expected.ts",
    "src/domain/fx-provider.ts",
    "src/domain/fx.ts",
    "src/domain/form-state.ts",
    "src/domain/input.ts",
    "src/domain/investment-projection.ts",
    "src/domain/investment-catalog.ts",
    "src/domain/installments.ts",
    "src/domain/investments.ts",
    "src/domain/logo-domain.ts",
    "src/domain/market.ts",
    "src/domain/money.ts",
    "src/domain/notifications.ts",
    "src/domain/onboarding.ts",
    "src/domain/privacy.ts",
    "src/domain/recurrence.ts",
    "src/domain/route-params.ts",
    "src/domain/serial-queue.ts",
    "src/domain/settings.ts",
    "src/domain/subscriptions.ts",
    "src/domain/transaction-draft.ts",
    "src/domain/transaction-search.ts",
    "src/domain/transactions.ts",
    "src/domain/types.ts",
    "src/domain/undo-outcome.ts",
    "src/domain/upcoming.ts",
    "src/domain/user-id.ts",
    "src/domain/user-error.ts",
    "src/domain/web-security.ts",
    "src/domain/year-columns.ts",
  ],
  ignorePatterns: [
    "/android/**",
    "/ios/**",
    "/dist/**",
    "/dist-e2e/**",
    "/.expo/**",
    "/.codex/**",
    "/.ai/**",
    "/.claude/**",
    "/docs/**",
    "/coverage/**",
    "/playwright-report/**",
    "/test-results/**",
  ],
  testRunner: "vitest",
  coverageAnalysis: "perTest",
  reporters: ["clear-text", "json"],
  jsonReporter: { fileName: "reports/mutation/mutation.json" },
  thresholds: { high: 99, low: 98, break: 98 },
  concurrency: 4,
  timeoutMS: 15_000,
  cleanTempDir: "always",
  vitest: { configFile: "vitest.mutation.config.ts", related: false },
};
