import { defineConfig } from "vitest/config";

// The modules that decide what a number means or what gets written. Files
// under `src/domain` and `src/data/repo` that are absent from this list score
// below the thresholds below and are not gated yet.
const criticalDomainFiles = [
  "src/data/repo/accounts.ts",
  "src/data/repo/categories.ts",
  "src/data/repo/cell-notes.ts",
  "src/data/repo/attachments.ts",
  "src/data/repo/computed.ts",
  "src/data/repo/errors.ts",
  "src/data/repo/import-plan.ts",
  "src/data/repo/matrix-colors.ts",
  "src/data/repo/installments.ts",
  "src/data/repo/investment-validation.ts",
  "src/data/repo/investments.ts",
  "src/data/repo/onboarding.ts",
  "src/data/repo/rule-validation.ts",
  "src/data/repo/rules.ts",
  "src/data/repo/settings.ts",
  "src/data/repo/statement-import.ts",
  "src/data/repo/transactions.ts",
  "src/domain/analytics.ts",
  "src/domain/app-guard.ts",
  "src/domain/attachments.ts",
  "src/domain/attention.ts",
  "src/domain/balance-declaration.ts",
  "src/domain/money.ts",
  "src/domain/balance.ts",
  "src/domain/budgets.ts",
  "src/domain/cash-flow-matrix.ts",
  "src/domain/card-statements.ts",
  "src/domain/computed-columns.ts",
  "src/domain/dashboard.ts",
  "src/domain/dates.ts",
  "src/domain/diagnostics.ts",
  "src/domain/expected.ts",
  "src/domain/fx-provider.ts",
  "src/domain/fx.ts",
  "src/domain/form-state.ts",
  "src/domain/input.ts",
  "src/domain/investment-projection.ts",
  "src/domain/investment-catalog.ts",
  "src/domain/installments.ts",
  "src/domain/matrix-colors.ts",
  "src/domain/matrix-preferences.ts",
  "src/domain/provenance.ts",
  "src/domain/recurrence.ts",
  "src/domain/save-summary.ts",
  "src/domain/statement-import.ts",
  "src/domain/transaction-draft.ts",
  "src/domain/investments.ts",
  "src/domain/market.ts",
  "src/domain/logo-domain.ts",
  "src/domain/notifications.ts",
  "src/domain/onboarding.ts",
  "src/domain/privacy.ts",
  "src/domain/route-params.ts",
  "src/domain/serial-queue.ts",
  "src/domain/settings.ts",
  "src/domain/subscriptions.ts",
  "src/domain/transaction-search.ts",
  "src/domain/transactions.ts",
  "src/domain/types.ts",
  "src/domain/undo-outcome.ts",
  "src/domain/upcoming.ts",
  "src/domain/user-id.ts",
  "src/domain/user-error.ts",
  "src/domain/web-security.ts",
  "src/domain/year-columns.ts",
];

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    environment: "node",
    coverage: {
      enabled: true,
      provider: "v8",
      include: criticalDomainFiles,
      reportsDirectory: "coverage/critical-domain",
      reporter: ["text", "json-summary"],
      reportOnFailure: true,
      skipFull: false,
      thresholds: {
        perFile: true,
        branches: 90,
        functions: 100,
        lines: 95,
        statements: 90,
      },
    },
  },
});
